# Generated by Django 4.2.3 on 2023-07-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_is_disabled_account_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_admin",
        ),
    ]
